### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by 7h0mas-R**
Had opened an issue because I misinterpreted the text in install instructions. The behavior I observed is not correctly described in the current text. Tried to change it so it still describes the original issue but also what to do if you observe the same problem that I saw. https://github.com/darktable-org/darktable/issues/14826

### CODE REVIEW

**Comment by paperdigits** [comment]
If method 2 works for both situations, we should just recommend that.

**Comment by 7h0mas-R** [comment]
For non-techies the first method without having to hack commands into the terminal may feel less "invasive".  It is also not permanent, so I would still prefer it, if it would still work.
So I'd tend to leave it up to the user, what works better in their particular case.

**Comment by victoryforce** [comment]
I second @7h0mas-R's point of view. Not all users are advanced or techies. There are people who are frightened by the need to enter some commands in the command line. There are people who are so unfamiliar with this that they can't understand that for example <path/to/application.app> doesn't need to be typed literally... It's better to take this into account and provide an alternative that doesn't involve typing commands.

**Comment by TurboGit** [comment]
Another point of view is that it is insane from Apple to ask for more that 100$/year for a key to sign software. That's a negative and hostile position from them against Open Source, so maybe it is time for people to move away.

Sorry, I know I'm not going to get only friends by saying this :)

**Comment by 7h0mas-R** [comment]
Even as convinced Apple user I see your point. But wasn't the "fee waiver" intended exactly for such situations? Organizations and entities providing free software?
Can't judge, how difficult it is to get admission and if it would work for Darktable, but I read about it in the press. The problem may be the level of organization though, not sure if there is a legal entity existing (person or org), that could apply for Darktable. I know it doesn't really belong here-maybe worth to bring to the attention of users-could be there is somebody experienced with Apple Developer Program fee waivers in the user community and willing to support? Might be a topic for the blog?

**Comment by paperdigits** [comment]
pixls.us has sponsored apple dev memberships for other projects so the binaries can be signed.

If the macos builder is interested, do have them get in touch.

**Pull request merged**
