### PR TITLE
make the intent of the soft clearer

### PR DESCRIPTION
**Pull request by aurelienpierre**
As discussed on IRC, this adds a clear warning on darktable being an expert-oriented software, in an attempt to set users expectations right (expect a learning curve to handle the power, not intuitivity and predigested features) and not pose as a Lightroom clone.

### CODE REVIEW

**Comment by Nilvus** [comment]
Just needed, thanks !

**Comment by darix** [comment]
TBH i wont agree with this.

**Comment by darix** [comment]
why? because it can and will discourage users. and I think this is always wrong.

**Comment by aurelienpierre** [comment]
> because it can and will discourage users. and I think this is always wrong.

Discouraging users that are not willing to embrace the learning curve is not wrong. Over the past 2 years, too many users have switched from Lightroom to darktable as if it was only a cheap clone. They expected the same ergonomy and the 2-clicks magic of Lightroom, then later got frustrated when it never happened, and finally spread their frustration all over the internets. (frustration == unmet expectations).

We have nothing to sell here, if users get discouraged by the headline on the home page, they will never have the courage to go through the documentation anyway, so better save everyone's time. To me, it's only a matter of setting expectations right and stating clearly what darktable is and is not.

darktable is not user-friendy, it's not easy to use and not intended for beginners.

**Comment by Nilvus** [comment]
Maybe use "advanced" instead of "expert" could be a good compromise.

**Comment by patdavid** [comment]
I took a stab at re-wording the copy - maybe something like this would be helpful?

>darktable is an advanced, open-source photography workflow application intended to provide a powerful suite of tools for users.
It provides a virtual lighttable and darkroom for photographers and unparalleled control over the image processing pipeline.
It manages your digital negatives in a database and lets you view, develop, and enhance raw images.
>
>darktable is oriented towards users comfortable with advanced processing workflows. Newcomers may benefit from spending some time with the [manual][] to get acquainted with the project.

[manual]: https://www.darktable.org/resources/

**Comment by darix** [comment]
:+1: @patdavid

**Comment by Nilvus** [comment]
> I took a stab at re-wording the copy - maybe something like this would be helpful?
> 
> > darktable is an advanced, open-source photography workflow application intended to provide a powerful suite of tools for users.
> > It provides a virtual lighttable and darkroom for photographers and unparalleled control over the image processing pipeline.
> > It manages your digital negatives in a database and lets you view, develop, and enhance raw images.
> > darktable is oriented towards users comfortable with advanced processing workflows. Newcomers may benefit from spending some time with the [manual](https://www.darktable.org/resources/) to get acquainted with the project.

A better suggestion. Thanks for that. A good compromise between what is needed and proposed by @aurelienpierre and welcoming new users by advertising them. I'm on for that !

**Comment by aurelienpierre** [comment]
I still think we need to mention somewhere that the entry fee is the learning curve. @patdavid's copy is a bit too polite for my taste.

It took me 3 years to learn how to use that software properly, and only 2 months to learn how to hack it in C. We need to be upfront about that. The UX is sub-optimal, the UI is messy, the workflow is not seamless and, if you don't know what you are doing, expect no safety jacket to save you because there is none.

Let's not be the same FOSS fools than those who pretend Linux is for everybody and doesn't require to use the terminal.

**Comment by darix** [comment]
So maybe we should invest some more time on the documentation then?

**Comment by aurelienpierre** [comment]
People don't RTFM. That's a fact. They randomly push sliders until they are happy, or give up after a while if they are not. They just assume the software should be "intuitive", which is kind of impossible with no prior knowledge. I have written 3 A4 pages of doc for filmic, and still get emails about stuff answered in there. Human children spend 2-3 years learning how to walk, how an image processing soft is ever supposed to be intuitive with no background ?

There are 2 things at work here:

1. learn how to post-process a picture, which is independent from any software but linked only to the basics of image processing (optics, electronics, psychophysics & colour science) and legacy film/darkroom workflow, aka hardcore theory,
2. learn how to operate a given software in order to post-process a picture, aka pure practice.

The problem is most people in darktable's audience will need to learn both at the same time, since they have no background, and also learn the difference between both, to not get lost between the software specifics and the general guidelines of image processing.

No documentation will ever address that, it's worth a full bachelor of arts. There is this false belief everywhere that, as software is becoming better, we can spare the theory & technics learning, but it's dead wrong and the complexity of everything is just increasing step by step as algos become more powerful.

For now, learning darktable is a lot of lonely effort, crossing sources between the documentation, courses, tutorials, blogs, forums and lots of personal tests until it all converges toward a usable workflow based on some understanding of what's going on at a relatively low level.

**Comment by darix** [comment]
here is the fun part ... I am working on darktable because it was the most easily approachable solution when I was looking for a photo editing solution on linux. and it still is imho. (although I have to say I liked the old filmic module better than the new one. but I probably need to RTFM a bit more)

and imho ... using the argument "some users dont read the docs and we want to discourage them not to start with darktable at all" is not a good attitude.

**Comment by aurelienpierre** [comment]
> and imho ... using the argument "some users dont read the docs and we want to discourage them not to start with darktable at all" is not a good attitude.

I disagree. Don't promise more than you can deliver. We don't deliver an easy soft (or even a well-designed, for that matter), so state that clearly and let users make their own choice based on reliable info. If you trap them into your user-base with sweetened info and they get discouraged after a while, you will have lost everybody's time and turned discouragement into anger. 

darktable gives you the power to do whatever you like to your pictures, including great stuff and shooting yourself in the foot. That's all.

Users who just want to do minor edits like contrast and saturation may be lucky with just slider pushing, although most of them will find the soft too complex and overhelming, with settings named with their technical name instead of a general-audience translation (Lightroom-style). 

Users who are after a precise look, an efficient and reproducible workflow, and/or need to reconstruct damaged images (noise, clipped areas, dust, etc.) will need to pay the entry fee: time to learn. 

Users who get discouraged by a tagline on an home page will never make it through the doc anyway. I'm a firm believer in social Darwinism here.

**Comment by houz** [comment]
I prefer @patdavid's version, too. Saying that dt is aimed at experts is wrong, it is a general purpose raw developer aimed at everyone who wants to use it. That being said, I really don't understand where the notion that dt's UI is bad is coming from.

**Comment by aurelienpierre** [comment]
>  Saying that dt is aimed at experts is wrong, it is a general purpose raw developer aimed at everyone who wants to use it. 

Right. LaTeX is also a general purpose text compositor aimed at anyone who wants to use it. It doesn't mean it's suitable for my grand-father. We need to be realistic. If beginners find darktable too complicated, it's probably because it is.

> That being said, I really don't understand where the notion that dt's UI is bad is coming from.

A good UI would guide users through a consistent workflow step by step. What we have is rather a collection of scattered plugins. Also, modules that perform low-level signal reconstruction should be clearly identified and separated from strictly artistic ones. Finally, I used dt for like 7 years before opening its source code, only to find that I understood many parts wrong or partially, especially the working color spaces or the assumptions made on the signal in modules.

**Comment by rabauke** [comment]
I totally agree with the general intention of the changes by @aurelienpierre . Nevertheless, the wording `expert-orientated` is too strong in my view. When does somebody qualify as an expert? 

Therefore, I tend to prefer the text as suggested by @patdavid with some minor changes (**_highlighted_**):

darktable is an advanced, open-source photography workflow application intended to provide a powerful suite of tools for **_ambitious_** users. It provides a virtual lighttable and darkroom for photographers and unparalleled control over the image processing pipeline. It manages your digital negatives in a database and lets you view, develop, and enhance raw images.

darktable is oriented towards users comfortable with advanced processing workflows. Newcomers **_will_** benefit from spending some time with the manual to get acquainted with the **_software and basic concepts_**.

**Comment by paperdigits** [comment]
I've floated this a few times in the IRC:

darktable is a raw processing application for photographers who enjoy the mechanics of their craft.

**Comment by wubwubwubwubwubwubwubwub** [comment]
I have two thoughts that occurred to me while reading through this discussion.
The first is that a "professional users" label is catnip for certain kinds of unskilled users.  FWIW.
The second is that I'm pretty sure I'm the guy aurelienpierre is describing.  I have no prior image processing experience.  Makes me wonder where I might have missed the opportunity before...  And, yup, I push sliders and turn knobs to see what happens.  I don't have a theoretical conceptual framework to help me attempt to process difficult images (they always remind me of advice from a professional photographer I once heard give a talk, "Don't take s*&#.")  A few days ago, I decided to make yet another attempt to educate myself, in part by looking at the resources available on the web site.  Unfortunately, the links from the list of modules to blog articles explaining how they really work were broken.  I have developed a great deal of respect for the folks on the team, since even with careful reading and attempting tutorials here and contained in the YouTube videos I'm going to revisit next, I still have not been able to correct my theoretical deficiencies.  It seems like there may be an understanding gap here that I will never be able to cross.  I consider myself fairly trainable, and I do take advantage of educational opportunities when I find them, but I guess I have quite a lot more searching ahead of me before I can use darktable with serious intent.
Won't stop me processing images, though, just makes me a bit sad that I am stuck wading in the shallow end of the pool.

**Comment by elstoc** [comment]
It's been four years and we don't have an auto-closure bot, so I'm gonna do it.

**Pull request closed without merging**
