### PR TITLE
3.8 blog post.

### PR DESCRIPTION
**Pull request by paperdigits**
Initial draft of the blog post.

If you want to propose changes, please request a specific change to the file, as detailed in [step 6 of the Github reviewing a PR documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)

Addresses #166.

### CODE REVIEW

**Comment by elstoc** [comment]
For some reason when I build this locally I can't see the new article on the blog page.

**Comment by bilddateien** [comment]
> For some reason when I build this locally I can't see the new article on the blog page.
> Actually I see you have to change the date on index.md to a date in the past for it to work.

You may use `hugo server -w -F --disableFastRender` with the `-F`option to show future articles

Btw.: German version of this article will be at https://www.bilddateien.de/blog/2021-12-24-darktable-3-8-tastaturbefehle-ueberall.html

**Comment by elstoc** [comment]
Thanks I worked that one out. I probably should have posted a comment. I'll add a link to the translation.

**Comment by elstoc** [comment]
ToDo: remove the words "perhaps" and "maybe" once we've done the final update to dtdocs.

**Pull request merged**
