### PR TITLE
Final version of darktable 3.0 article

### PR DESCRIPTION
**Pull request by Nilvus**
Here it is, ready to be published, the usual annual article by Moy. As he lacks some time this year, I see with him to make it, with the help of french community of darktable.fr.

Of course, this has to be published on darktable 3.0 release only, not before. Thanks.

### CODE REVIEW

**Comment by patdavid** [comment]
Can you please comment here and "@" mention me when it's ready to be merged?

**Comment by Nilvus** [comment]
> Can you please comment here and "@" mention me when it's ready to be merged?

Ok, It will be easy as I'm on with @TurboGit to prepare all of this. I will also propose a new capture screen for home screen (the actual one will be quite obsolete with the new UI on darktable 3.0).

**Comment by TurboGit** [comment]
@Nilvus : Great job ! I'll try to have a look at this tomorrow.

**Comment by Nilvus** [comment]
I've just made a last check and see that on darktable 2.6 images were centered. I didn't even think that alignment was possible in markdown (it's not possible with linuxfr markdown options). So I will update that tomorrow.

**Comment by Nilvus** [comment]
> Looks good to me! This can be merged just after the 3.0 announcement that I'll prepare for the release. Or maybe @Nilvus will want to delay it? Anyway I'll let @Nilvus give the GO for the publishing this.

No delay. It's ready to be merged when you will make the 3.0 announcement.

**Comment by moy** [comment]
IMHO, best is to have both the 3.0 announcement (with short release notes) and this article in the same PR, both articles cross-linking to each other. IIRC this is what we did last year.

**Comment by Nilvus** [comment]
@patdavid: I will propose a new screenshot (with the new UI) to replace the actual one of darktable.org home screen. Is it ok for you if I add it on this PR or do you prefer a separate one ?

@moy: I'm seeing this with @TurboGit.

**Comment by moy** [comment]
I can't generate the HTML from this on my machine. Not sure whether my Pelican install is broken or if it's an issue with the article itself. Did anyone manage to generate the site with the article? If so, can you post it somewhere so I can read directly the rendered article? If not, no problem, I'll read it after publishing.

I already fixed a few typos (no real proofreading, essentially a spellchecker actually) in https://github.com/Nilvus/dtorg/pull/3.

**Comment by Nilvus** [comment]
> I can't generate the HTML from this on my machine. Not sure whether my Pelican install is broken or if it's an issue with the article itself. Did anyone manage to generate the site with the article? If so, can you post it somewhere so I can read directly the rendered article? If not, no problem, I'll read it after publishing.
> 
> I already fixed a few typos (no real proofreading, essentially a spellchecker actually) in [Nilvus#3](https://github.com/Nilvus/dtorg/pull/3).

I have tested it with a local Pelican install. Article was ok.

**Comment by Nilvus** [comment]
Integrated in PR #86

**Pull request closed without merging**
