### PR TITLE
Update logdir in faq.md

### PR DESCRIPTION
**Pull request by esq4**
addition to https://github.com/darktable-org/darktable/commit/864923d1ebdb223a244b1e049f4157bf95ab3091

### CODE REVIEW

**Comment by paperdigits** [comment]
Awesome, thanks. It looks like this is for version >5.0 and I think it should be noted as such. Also for now, I don't think we want to loose the old paths.

**Comment by paperdigits** [comment]
Not sure why you deleted this, as it just need to be changed slightly to included the old path and the new path.

**Comment by esq4** [comment]
@paperdigits I decided to tidy up my branches and ended up losing the commit :-/

**Comment by paperdigits** [comment]
You can still see the change here: https://github.com/darktable-org/dtorg/pull/258/files 

:D

**Comment by esq4** [comment]
> You can still see the change here: https://github.com/darktable-org/dtorg/pull/258/files

Yes, but I made some changes.

**Comment by esq4** [comment]
I lost the battle with GitHub and made a new PR.

**Pull request closed without merging**
