### PR TITLE
Removing TIFF issue, as it has been fixed

### PR DESCRIPTION
**Pull request by peterbud**
Also adding language preference UI to the description

### CODE REVIEW

**Comment by moy** [comment]
Perhaps keeping the FAQ entry but changing the end to stg like "we have identified the root cause in an upstream system and fixed it in darktable 2.x.y." would help people getting the issue with an old darktable version.

**Comment by houz** [comment]
@moy Good point. And it's not even that we fixed it in darktable at all, we are just bundling a fixed exiv2 since 2.4.1.

**Comment by peterbud** [comment]
I thought this should be a FAQ, referring to the _latest_ available release.
IMHO FAQ section is not meant to people who do use old version of darktable, and to support my suggestion, I don't see any other similar content in the FAQ referring to the development process or already fixed bugs.

**Comment by houz** [comment]
The FAQ should answer whatever we are asked often. And if many Windows users still use the second latest release then we should keep it in. Maybe the way forward is to leave the FAQ as it is for now and merge this PR once we have 2.4.2 out?

**Comment by peterbud** [comment]
ok!

**Comment by moy** [comment]
For a real-life example: I got a complain on the french forum about TIFF export on Windows, and wanted to reply to the complain "look, this is fixed in the latest version, just upgrade" with a link for more information. I could not link to a place other than this PR: the current FAQ says "may be fixed in the future", which doesn't help. The FAQ after merging this would not mention the issue.

I don't think it's safe to assume that people will always run the very latest version. They upgrade when they have a good reason to do so, and the FAQ may give them one such good reason.

**Comment by peterbud** [comment]
Hi @moy , what if you would refer this user to the [Release Notes](https://github.com/darktable-org/darktable/releases/tag/release-2.4.1)? That clearly contained that we have a solution for that issue.

Maybe we could establish some guidelines for us:

- What is the purpose and appropriate content for FAQ?
- What is the purpose and appropriate content for Release Notes?
- What is the purpose and appropriate content for User Guide?

I'm fine with any setup if we don't duplicate content.

**Pull request closed without merging**
