### PR TITLE
add blog post about gamut mapping

### PR DESCRIPTION
**Pull request by aurelienpierre**

### CODE REVIEW

**Comment by elstoc** [comment]
As discussed needs a copy-edit before merging. I can probably take a look tomorrow some time.

**Review by Jiyone — CHANGES_REQUESTED** [review]
Some things may be confusing about where to save the icc file

**Comment by paperdigits** [comment]
@aurelienpierre I made a few edits, let me know when you're ready to merge.

**Comment by elstoc** [comment]
overtaken by events

**Pull request closed without merging**
