### PR TITLE
migrate website to hugo

### PR DESCRIPTION
**Pull request by robbymilo**
Initial port of the darktable website to [hugo](https://gohugo.io/). See https://github.com/darktable-org/dtorg/issues/113 for background.

I've been able to convert most of the markdown and layout files to a hugo compatible format. There are numerous ways to accomplish things with hugo, so I'd love recommendations if there's a better/easier way to do something here.

Notes:
- Uses hugo version `0.83.1`
- Uses GitHub actions to deploy a Netlify preview at https://hugo-robbymilo--darktable.netlify.app (can consider using [Netlify's open source plan](https://www.netlify.com/legal/open-source-policy/))
- Adds responsive images for some of the ledes/backgrounds. Note I am not committing most of the rendered thumbnails to git despite hugo's recommendation.
- I've kept the old theme files and .py scripts for reference, these can probably be removed.

To-do list for parity with the current website:

- [x] Handle posts with different slugs - either redirect old urls (alias?) or add a `slug` param with the proper value. For example, the current site renders as [/2020/08/darktable-321-released/](https://www.darktable.org/2020/08/darktable-321-released/), but hugo renders as [/2020/08/darktable-3.2.1-released/](https://hugo-robbymilo--darktable.netlify.app/2020/08/darktable-3.2.1-released/)
- [ ] Current search allows for searching the lua api - where are these located? Are these pages a different site?
- [x] Correct footer menu links
- [ ] Check for correct rendering of markdown - I've spot checked some of the articles and it looks like there may be some differences in how hugo (goldmark) renders markdown. For example, hugo does not render markdown within HTML. I've solved this by adding a shortcode. See https://github.com/robbymilo/dtorg/blob/robbymilo/hugo/content/blog/2020-08-10-darktable-3.2/index.md for an example with shortcodes.
- [ ] Check for broken links/images

To test locally:
- Make sure you have the correct hugo version installed. Run `make server` and navigate to localhost:1313

Feel free to add to the to-do list, or even better a to-do and solution :) 

cc @paperdigits

### CODE REVIEW

**Comment by paperdigits** [comment]
- [] Have solutions for all pelican plugins
  - [] article_metadate
  - [] attach_lede_image
  - [] image_compare
  - [] image_links
  - [] render_math
  - [] rm_nbsp_title
  - [] social_media
  - [] static_comments
  - [] summary
  - [] tipue_search

**Comment by paperdigits** [comment]
I've spent about the last 2 hours looking over this with the current site and your port side by side, and damn, this is impressive.

**Comment by paperdigits** [comment]
hey @robbymilo what's happening? :dancers:

**Comment by robbymilo** [comment]
@paperdigits hoping to find some time to work on this soon.

**Comment by robbymilo** [comment]
Here is a preview for the `image_compare` replacement (I think this is the only page with a compare?): https://hugo-robbymilo--darktable.netlify.app/2017/11/local-laplacian-pyramids/

**Comment by paperdigits** [comment]
@robbymilo I'm stupid, but I pushed a few commits to https://github.com/darktable-org/dtorg/tree/robbymilo-robbymilo/hugo

Is the option enabled in github so I can push commits (as a maintainer) to this PR?

**Comment by robbymilo** [comment]
@paperdigits I added you as a maintainer to https://github.com/robbymilo/dtorg - does that work?

**Comment by paperdigits** [comment]
Yes, that should work, thanks!

On March 22, 2021 11:04:51 AM PDT, Robby Milo ***@***.***> wrote:
***@***.*** I added you as a maintainer to

**Comment by paperdigits** [comment]
@robbymilo doh! I didn't accept the invitation soon enough... would you be kind enough to send me another?

**Comment by robbymilo** [comment]
@paperdigits sent!

**Comment by paperdigits** [comment]
I think as far as the hugo stuff goes, we're almost done.

Last thing is: handle posts with different slugs - I'd want to use the alias feature from hugo.

**Comment by patdavid** [comment]
This is impressive work, indeed!  I can't thank you enough @robbymilo for all of this work! :smile: 

I just pulled the site and things look really great locally with Hugo.
I know that @paperdigits  wanted to check URL's to make sure all the slugs either matched or take advantage of Hugo redirection for ones that do not.  Does anyone have a good command we can use to generate a recursive list of all URLs for the site?  something something wget something recursive something?

**Comment by robbymilo** [comment]
@patdavid I think you can range through `.Site.AllPages` to get every page's `.RelPermalink`.

**Comment by patdavid** [comment]
@robbymilo I was thinking of the existing site first, actually.  I wanted to get all releveant URL's from the existing site to make sure there was a corresponding match in your port (and if there wasn't, to include a redirect frontmatter so hugo can redirect any old links to the correct slug/location).

**Comment by robbymilo** [comment]
@patdavid I've added a command (https://github.com/robbymilo/dtorg/blob/robbymilo/hugo/Makefile#L39) that takes all the .html files from the output folder of the current site, and then lists them in https://github.com/robbymilo/dtorg/blob/robbymilo/hugo/output.csv.

**Comment by paperdigits** [comment]
I think this is done. @patdavid can you think of anything else? If you or @robbymilo wants to make a last sanity check, please do!

**Comment by elstoc** [comment]
still needs to incorporate changes from #141 and #142

**Comment by patdavid** [comment]
Can we cherry pick those into the hugo branch?

**Comment by paperdigits** [comment]
@robbymilo I rebased this on master and resolved the conflicts, if you want to take a look at https://github.com/darktable-org/dtorg/tree/hugo

I couldn't figure out how to push that to this PR, and probably better I didn't since it rewrites history.

**Comment by elstoc** [comment]
@paperdigits the 3.6 blog post needs `{filename}` removing from the image links in the Hugo port.

**Pull request closed without merging**
