### PR TITLE
faq: observe English conventions

### PR DESCRIPTION
**Pull request by elstoc**
let battle commence...

### CODE REVIEW

**Comment by elstoc** [comment]
I'll admit I was expecting a bit of debate before this one was merged. Some (odd) people care very much about defying the conventions of the English language.

Of course now we've got to alter the rest of the website to conform.

**Comment by jade-nl** [comment]
I still think that darktable should be darktable, even at the beginning of a sentence. Am I odd.... Probably :-))

Have fun changing all the documentation, website(s) and what have you >:-)

**Comment by elstoc** [comment]
Documentation should be easy. I've only started sentences with "darktable" where I couldn't find any other way to do it, to avoid this problem.

**Comment by patdavid** [comment]
> I'll admit I was expecting a bit of debate before this one was merged. 

Yeah, no need to bikeshed this, imo.  Excelsior!

**Comment by elstoc** [comment]
The debate is happening on IRC now though.

**Comment by elstoc** [comment]
As an alternative, we could say "As such you should avoid starting a sentence with the word darktable". Of course people will, whatever we say, and we should try to avoid "correcting" them.

**Pull request merged**
