### PR TITLE
Added link to Spanish translation

### PR DESCRIPTION
**Pull request by criadoperez**
Added link to Spanish translation.
Link to this original post appears in the Spanish translation article.

### CODE REVIEW

**Comment by paperdigits** [comment]
Did you mean to add this link to the blog post rather than the news announcement? That's where the other translations are linked as well.

**Comment by criadoperez** [comment]
I added it the post. For some reason the post anouncing version 3.4.1 doesnt appear in the blog section like the rest, only on the news section. 
If I added it in the wrong place, please feel free to add the link wherever its appropiate instead.

**Comment by paperdigits** [comment]
Ah we only wrote a blog post for 3.4.0, not 3.4.1.

**Comment by criadoperez** [comment]
Not sure I understand, the next step.
Will we have the article in the blog also and there we can paste the translation?
Or a translation link is not possible and I cancel this Pull Request?

**Pull request merged**
